import type { AppUser, Organization, Video } from '../../types/models';
import { muxThumbnailUrl } from '../mux';

/**
 * Seed content used when no Firebase project is configured. The playback IDs are Mux's
 * public demo assets so the player is exercised end-to-end.
 *
 * The set deliberately includes `pending` and `rejected` videos: viewer-facing queries
 * must filter them out, and having them here keeps that guarantee honest.
 */

const MUX_DEMO_PLAYBACK_IDS = [
  'qxb01i6T202018GFS02vp9RIe01icTcDCjVzQpmaB00CUisJ4',
  'VZtzUzGRv02OhRnZCxcNg49OilvolTqdnFLEqBsTwaxU',
  'a4nOgmxGWg6gULfcBbAa00gXyfcwPnAFldF8RdsNyk8M',
  '23s11nz72DsoN6chXqk902M9VuUOaHFqvcYmC8I5Nwno',
];

const playbackId = (index: number) =>
  MUX_DEMO_PLAYBACK_IDS[index % MUX_DEMO_PLAYBACK_IDS.length];

const daysAgo = (days: number) =>
  new Date(Date.UTC(2026, 5, 1) - days * 86_400_000).toISOString();

export const DEMO_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-grace-chapel',
    name: 'Grace Chapel',
    description:
      'A neighbourhood church in Nashville teaching verse by verse through the Scriptures every Sunday.',
    logoUrl: 'https://api.dicebear.com/9.x/initials/png?seed=Grace%20Chapel&backgroundColor=0A1F44',
    verificationStatus: 'verified',
    contactEmail: 'media@gracechapel.example',
    ownerUserId: 'user-demo-org-owner',
    websiteUrl: 'https://gracechapel.example',
    location: 'Nashville, TN',
    followerCount: 18420,
    createdAt: daysAgo(900),
  },
  {
    id: 'org-cornerstone-worship',
    name: 'Cornerstone Worship',
    description:
      'Worship collective writing songs for the local church. Live recordings from our Friday night gatherings.',
    logoUrl:
      'https://api.dicebear.com/9.x/initials/png?seed=Cornerstone%20Worship&backgroundColor=132B57',
    verificationStatus: 'verified',
    contactEmail: 'hello@cornerstoneworship.example',
    ownerUserId: 'user-cornerstone',
    location: 'Dallas, TX',
    followerCount: 64110,
    createdAt: daysAgo(720),
  },
  {
    id: 'org-anchor-youth',
    name: 'Anchor Youth',
    description:
      'Discipling teenagers with honest conversations about faith, identity and the world they are growing up in.',
    logoUrl: 'https://api.dicebear.com/9.x/initials/png?seed=Anchor%20Youth&backgroundColor=1D3A6B',
    verificationStatus: 'verified',
    contactEmail: 'team@anchoryouth.example',
    ownerUserId: 'user-anchor',
    location: 'Manchester, UK',
    followerCount: 9350,
    createdAt: daysAgo(420),
  },
  {
    id: 'org-lantern-films',
    name: 'Lantern Films',
    description:
      'Independent studio producing feature films and documentaries rooted in the Christian story.',
    logoUrl: 'https://api.dicebear.com/9.x/initials/png?seed=Lantern%20Films&backgroundColor=8E1B1B',
    verificationStatus: 'verified',
    contactEmail: 'studio@lanternfilms.example',
    ownerUserId: 'user-lantern',
    location: 'Cape Town, ZA',
    followerCount: 27890,
    createdAt: daysAgo(365),
  },
  {
    id: 'org-still-waters',
    name: 'Still Waters Devotionals',
    description: 'Two-minute Scripture readings and prayers to start the morning.',
    logoUrl: 'https://api.dicebear.com/9.x/initials/png?seed=Still%20Waters&backgroundColor=2B4C82',
    verificationStatus: 'pending',
    contactEmail: 'mail@stillwaters.example',
    ownerUserId: 'user-still-waters',
    followerCount: 0,
    createdAt: daysAgo(6),
  },
];

type VideoSeed = Omit<Video, 'thumbnailUrl' | 'videoAssetId'> & { seedIndex: number };

const seeds: VideoSeed[] = [
  {
    id: 'vid-001',
    seedIndex: 0,
    orgId: 'org-grace-chapel',
    title: 'The God Who Sees You',
    description:
      'Hagar was alone in the wilderness when she gave God a name no one had used before: El Roi, the God who sees me. Part one of our summer series in Genesis on the people God notices when no one else does.',
    category: 'sermons',
    tags: ['genesis', 'hagar', 'summer series'],
    duration: 2_412,
    publishStatus: 'published',
    viewCount: 184_233,
    createdAt: daysAgo(3),
    isFeatured: true,
    speaker: 'Pastor Daniel Okoye',
  },
  {
    id: 'vid-002',
    seedIndex: 1,
    orgId: 'org-cornerstone-worship',
    title: 'Hymns at Midnight — Live Worship Night',
    description:
      'Ninety minutes of hymns reimagined, recorded live with our congregation on a Friday night in Dallas.',
    category: 'worship',
    tags: ['live', 'hymns', 'acoustic'],
    duration: 5_280,
    publishStatus: 'published',
    viewCount: 921_004,
    createdAt: daysAgo(1),
    isFeatured: true,
    isLive: true,
  },
  {
    id: 'vid-003',
    seedIndex: 2,
    orgId: 'org-lantern-films',
    title: 'Carry the Light',
    description:
      'A feature documentary following three families rebuilding their village church after the floods.',
    category: 'films',
    tags: ['documentary', 'feature', 'community'],
    duration: 4_920,
    publishStatus: 'published',
    viewCount: 342_889,
    createdAt: daysAgo(11),
    isFeatured: true,
  },
  {
    id: 'vid-004',
    seedIndex: 3,
    orgId: 'org-anchor-youth',
    title: 'Comparison Is a Thief',
    description:
      'What do you do when your whole feed is other people winning? An honest conversation with our Wednesday night group.',
    category: 'youth',
    tags: ['identity', 'social media'],
    duration: 1_680,
    publishStatus: 'published',
    viewCount: 58_120,
    createdAt: daysAgo(4),
    isFeatured: true,
  },

  {
    id: 'vid-010',
    seedIndex: 1,
    orgId: 'org-grace-chapel',
    title: 'When Prayer Feels Like Silence',
    description:
      'A message on persevering in prayer when heaven seems quiet, from Luke 18.',
    category: 'sermons',
    tags: ['prayer', 'luke'],
    duration: 2_150,
    publishStatus: 'published',
    viewCount: 74_002,
    createdAt: daysAgo(10),
    speaker: 'Pastor Daniel Okoye',
  },
  {
    id: 'vid-011',
    seedIndex: 2,
    orgId: 'org-grace-chapel',
    title: 'The Prodigal and the Older Brother',
    description: 'Two sons, one father, and the grace that offends us both.',
    category: 'sermons',
    tags: ['parables', 'grace'],
    duration: 2_760,
    publishStatus: 'published',
    viewCount: 132_540,
    createdAt: daysAgo(17),
    speaker: 'Pastor Ruth Adeyemi',
  },
  {
    id: 'vid-012',
    seedIndex: 3,
    orgId: 'org-anchor-youth',
    title: 'Sermon on the Mount, Part 4: Salt and Light',
    description: 'Jesus on what it looks like to be visibly different in an ordinary week.',
    category: 'sermons',
    tags: ['matthew', 'sermon on the mount'],
    duration: 1_980,
    publishStatus: 'published',
    viewCount: 41_209,
    createdAt: daysAgo(24),
  },

  {
    id: 'vid-020',
    seedIndex: 0,
    orgId: 'org-cornerstone-worship',
    title: 'Great Is Thy Faithfulness (Live)',
    description: 'A stripped-back arrangement led by our youth choir.',
    category: 'worship',
    tags: ['hymn', 'live'],
    duration: 412,
    publishStatus: 'published',
    viewCount: 1_204_881,
    createdAt: daysAgo(7),
  },
  {
    id: 'vid-021',
    seedIndex: 2,
    orgId: 'org-cornerstone-worship',
    title: 'Morning Set — Acoustic Sessions Vol. 3',
    description: 'Six songs recorded in one take, no overdubs, in an empty sanctuary at sunrise.',
    category: 'worship',
    tags: ['acoustic', 'sessions'],
    duration: 1_845,
    publishStatus: 'published',
    viewCount: 388_450,
    createdAt: daysAgo(14),
  },
  {
    id: 'vid-022',
    seedIndex: 1,
    orgId: 'org-grace-chapel',
    title: 'Psalms of Ascent — Congregational Night',
    description: 'Singing the songs the pilgrims sang on the way up to Jerusalem.',
    category: 'worship',
    tags: ['psalms', 'congregational'],
    duration: 3_120,
    publishStatus: 'published',
    viewCount: 96_310,
    createdAt: daysAgo(21),
  },

  {
    id: 'vid-030',
    seedIndex: 3,
    orgId: 'org-grace-chapel',
    title: 'How to Read the Old Testament',
    description: 'A practical four-part class on reading the first two-thirds of your Bible well.',
    category: 'teaching',
    tags: ['bible study', 'old testament'],
    duration: 3_600,
    publishStatus: 'published',
    viewCount: 210_770,
    createdAt: daysAgo(5),
  },
  {
    id: 'vid-031',
    seedIndex: 0,
    orgId: 'org-lantern-films',
    title: 'The Councils That Shaped the Creed',
    description: 'A short history of Nicaea and Chalcedon, and why the wording still matters.',
    category: 'teaching',
    tags: ['church history', 'creeds'],
    duration: 2_280,
    publishStatus: 'published',
    viewCount: 63_442,
    createdAt: daysAgo(30),
  },
  {
    id: 'vid-032',
    seedIndex: 1,
    orgId: 'org-anchor-youth',
    title: 'Apologetics for Ordinary Conversations',
    description: 'Answering hard questions without turning every dinner into a debate.',
    category: 'teaching',
    tags: ['apologetics'],
    duration: 1_920,
    publishStatus: 'published',
    viewCount: 38_004,
    createdAt: daysAgo(35),
  },

  {
    id: 'vid-040',
    seedIndex: 2,
    orgId: 'org-anchor-youth',
    title: 'Friday Night Live: Sent',
    description: 'Worship, testimony and teaching from our end-of-term gathering.',
    category: 'youth',
    tags: ['live', 'gathering'],
    duration: 4_080,
    publishStatus: 'published',
    viewCount: 27_890,
    createdAt: daysAgo(8),
  },
  {
    id: 'vid-041',
    seedIndex: 3,
    orgId: 'org-anchor-youth',
    title: 'Real Talk: Anxiety and Faith',
    description: 'A counsellor and a youth pastor answer questions students actually sent in.',
    category: 'youth',
    tags: ['mental health', 'q&a'],
    duration: 2_040,
    publishStatus: 'published',
    viewCount: 112_330,
    createdAt: daysAgo(19),
  },

  {
    id: 'vid-050',
    seedIndex: 0,
    orgId: 'org-lantern-films',
    title: 'Twelve Years, One Prayer',
    description: 'Marcus tells the story of the decade he spent away, and the night he came home.',
    category: 'testimonies',
    tags: ['story', 'redemption'],
    duration: 960,
    publishStatus: 'published',
    viewCount: 501_223,
    createdAt: daysAgo(2),
  },
  {
    id: 'vid-051',
    seedIndex: 1,
    orgId: 'org-grace-chapel',
    title: 'From the Ward to the Pulpit',
    description: 'A nurse on finding calling in the middle of the hardest year of her life.',
    category: 'testimonies',
    tags: ['calling', 'story'],
    duration: 720,
    publishStatus: 'published',
    viewCount: 88_991,
    createdAt: daysAgo(13),
  },

  {
    id: 'vid-060',
    seedIndex: 2,
    orgId: 'org-lantern-films',
    title: 'Ordinary Saints',
    description:
      'A 78-minute feature following four believers in four cities through one ordinary week.',
    category: 'films',
    tags: ['feature', 'drama'],
    duration: 4_680,
    publishStatus: 'published',
    viewCount: 176_004,
    createdAt: daysAgo(45),
  },
  {
    id: 'vid-061',
    seedIndex: 3,
    orgId: 'org-lantern-films',
    title: 'The Letter Writer',
    description: 'Short film. A retired postman keeps delivering one address that no longer exists.',
    category: 'films',
    tags: ['short film'],
    duration: 1_500,
    publishStatus: 'published',
    viewCount: 62_118,
    createdAt: daysAgo(52),
  },

  {
    id: 'vid-070',
    seedIndex: 0,
    orgId: 'org-grace-chapel',
    title: 'Morning Devotional: Psalm 23',
    description: 'Three minutes in the shepherd psalm to begin your day.',
    category: 'devotionals',
    tags: ['psalms', 'morning'],
    duration: 210,
    publishStatus: 'published',
    viewCount: 445_002,
    createdAt: daysAgo(1),
  },
  {
    id: 'vid-071',
    seedIndex: 1,
    orgId: 'org-cornerstone-worship',
    title: 'Evening Prayer: Compline',
    description: 'A sung liturgy to close the day.',
    category: 'devotionals',
    tags: ['liturgy', 'evening'],
    duration: 480,
    publishStatus: 'published',
    viewCount: 133_450,
    createdAt: daysAgo(9),
  },
  {
    id: 'vid-072',
    seedIndex: 2,
    orgId: 'org-anchor-youth',
    title: '5 Minutes in Romans 8',
    description: 'No condemnation — a short reading and reflection.',
    category: 'devotionals',
    tags: ['romans', 'short'],
    duration: 300,
    publishStatus: 'published',
    viewCount: 76_220,
    createdAt: daysAgo(16),
  },

  // Moderation queue — these must never surface in viewer-facing queries.
  {
    id: 'vid-900',
    seedIndex: 0,
    orgId: 'org-grace-chapel',
    title: 'Midweek Service — Awaiting Review',
    description: 'Uploaded but not yet approved by the SetApart review team.',
    category: 'sermons',
    tags: ['midweek'],
    duration: 2_100,
    publishStatus: 'pending',
    viewCount: 0,
    createdAt: daysAgo(1),
  },
  {
    id: 'vid-901',
    seedIndex: 1,
    orgId: 'org-anchor-youth',
    title: 'Youth Retreat Raw Footage',
    description: 'Rejected: unlicensed background music.',
    category: 'youth',
    tags: [],
    duration: 1_260,
    publishStatus: 'rejected',
    viewCount: 0,
    createdAt: daysAgo(20),
  },
];

export const DEMO_VIDEOS: Video[] = seeds.map(({ seedIndex, ...video }) => {
  const assetId = playbackId(seedIndex);
  return {
    ...video,
    videoAssetId: assetId,
    thumbnailUrl: muxThumbnailUrl(assetId, { width: 720, time: 4 + seedIndex * 3 }),
  };
});

export const DEMO_USER: AppUser = {
  id: 'user-demo-viewer',
  displayName: 'Demo Viewer',
  email: 'viewer@setapart.app',
  roles: ['viewer'],
  favoriteVideoIds: ['vid-020', 'vid-050'],
  watchLaterVideoIds: ['vid-060'],
  followedOrgIds: ['org-grace-chapel', 'org-cornerstone-worship'],
  watchHistory: [
    { videoId: 'vid-001', watchedAt: daysAgo(0), positionSeconds: 640 },
    { videoId: 'vid-070', watchedAt: daysAgo(1), positionSeconds: 210 },
  ],
  createdAt: daysAgo(120),
};
